name: Format and lint code
on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize
jobs:
  format-lint:
    name: format-lint
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node ${{ matrix.node }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node }}
      - name: Install dependencies
        run: npm ci
      - name: Format code
        run: npm run format
      - name: Lint code
        run: npm run lint
